name: Deploy Bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  sync_to_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build config template
        run: |
            cat > .env <<'EOF'
            TOKEN="${{ secrets.BOT_DISCORD_TOKEN }}"
            GITHUB_TOKEN="${{ secrets.BOT_GITHUB_TOKEN }}"
            EOF

      - name: Deploy to VPS
        run: |
          ssh-keyscan -H ${ secrets.DEPLOY_HOST } >> ~/.ssh/known_hosts
          ssh -o "StrictHostKeyChecking=no" -i ${ secrets.DEPLOY_KEY } ${ secrets.DEPLOY_USER }@${ secrets.DEPLOY_HOST } "mkdir -p ${ secrets.DEPLOY_PATH } && cd ${ secrets.DEPLOY_PATH } && rm -rf * && git clone https://github.com/${ github.repository } .git && cd ${ github.repository } && git checkout ${ github.event_name } && git pull && git reset --hard origin/${ github.event_name } && cp -r ./* ${ secrets.DEPLOY_PATH }"
